# -*-ruby-*-

require 'rake/clean'
require 'rake/testtask'
require 'bundler/gem_tasks'
gem 'rdoc'
require 'rdoc/task'

task default: [:test]

RDoc::Task.new('html') do |i|
  i.main = 'doc/README.rdoc'
  i.rdoc_files = FileList['doc/*', 'lib/**/*.rb']
#  i.rdoc_files.exclude("lib/**/some-nasty-staff")
end

Rake::TestTask.new do |i|
  i.test_files = FileList['test/test_*.rb']
end
